Bitbucket on prem/init api
Rookout/explorook pull request #207
Opened 2020-09-13 13:42 UTC by dan505512

Adding queries for bitbucket on prem. Works on my machine

2020-09-13 13:43 UTC, dan505512 commented
RK-7017

2020-09-14 12:03 UTC, dan505512 commented
@amits1995 Fixed the api. Sending you all the queries on Slack so you can see how it looks

2020-09-14 13:02 UTC, amits1995 requested changes
Stricter parameters and some minors

2020-09-17 12:57 UTC, dan505512 commented on src/BitBucketOnPrem.ts
> +    const file = await res.json();
No other way

2020-09-21 09:03 UTC, amits1995 requested changes

2020-09-21 09:03 UTC, amits1995 commented on src/utils.ts
> +    if (!areOnPremServersValid(settings?.BitbucketOnPremServers)) {
move to constraint directive (easily done with https://www.npmjs.com/package/graphql-constraint-directive#pattern)

2020-09-21 09:03 UTC, amits1995 commented on src/utils.ts
> +    if (!areOnPremServersValid(settings?.BitbucketOnPremServers)) {
2. no need to always override the servers settings

2020-09-21 12:03 UTC, amits1995 commented on src/BitBucketOnPrem.ts
> +    const file = await res.json();
sad reacts only

2020-09-24 09:20 UTC, amits1995 submitted a review, later dismissed

2020-09-27 07:24 UTC, amits1995 approved these changes

2020-09-27 07:25 UTC, merged