Fix Snyk Vulnerabilities - August 21
Rookout/explorook pull request #285
Opened 2021-09-01 16:34 UTC by moryakub

Tested against local rookout deployment.
Validated:
1. bitbucket OP fetching works
2. loading new repos still works
3. deleting previously loaded repos still works

2021-09-01 16:34 UTC, moryakub commented
RK-9991

2021-09-02 07:10 UTC, niryarden requested changes
in explorook you need to bump up the version in package.json in every PR.
but wait a few hours with please and let me merge the two other PRs, so we won't get messed up with the versions

2021-09-02 12:16 UTC, niryarden commented
@moryakub you're free to go - pull origin master and bump the version

2021-09-05 08:53 UTC, niryarden approved these changes

2021-09-05 12:39 UTC, merged